updated build hooks

diff --git a/hooks/env b/hooks/env
--- a/hooks/env
+++ b/hooks/env
@@ -9,7 +9,10 @@ QEMU_DIR='.qemu_static'
 IMPORTS_DIR='.imports'
 
 ARCH_YAML='arch.yaml'
-CONFIG_YAML="${DATA_DIR}/config.${DOCKER_TAG}${CONFIG_SUFFIX}.yaml"
+CONFIG_YAML="${CONFIG_YAML_OVERRIDE:-${DATA_DIR}/config.${DOCKER_TAG}${CONFIG_SUFFIX}.yaml}"
+
+# names of debian releases
+debian_names=('null' 'buzz' 'hamm' 'woody' 'etch' 'lenny' 'squeeze' 'wheezy' 'jessie' 'stretch' 'buster' 'bullseye' 'bookworm' 'trixie')
 
 #BUILD_PLATFORM_ARG='true'
 
@@ -23,6 +26,7 @@ CACHE_EXPIRY=604800
 DOCKER_FILE='Dockerfile'
 
 [ ! -d "${DATA_DIR}" ] && mkdir -p "${DATA_DIR}"
+[ ! -f "${CONFIG_YAML}" ] && touch "${CONFIG_YAML}"
 
 ## import config for this repo
 . "build.conf" || { echo 'No build.conf!'; exit 1; }
@@ -32,7 +36,7 @@ DOCKER_FILE='Dockerfile'
 #	add_param       <value> <param>
 #	print_param     <value> <desc>
 #	add_print_param <value> <param> <desc>
-del_param() { sed "/${1}/d" -i "${CONFIG_YAML}"; }
+del_param() { sed "/^${1}:/d" -i "${CONFIG_YAML}"; }
 add_param () {
 	local value
 	value="$(echo "${1}" | xargs)"
@@ -43,34 +47,81 @@ add_param () {
 print_param () { printf '%-40s %-8s\n' "${2}" "${1}"; }
 add_print_param () { add_param "${1}" "${2}"; print_param "${1}" "${3:-${2}}"; }
 
-# only execute code to determine the parameter if it's unset, otherwise use the
-# existing set value
+# similar to the commands above, but do an 'eval' here so we don't need to use
+# "$(..)" when calling the function
+#
+# the 'ifn' functions only execute code to determine the parameter if it's unset,
+# otherwise using the existing set value
 #
 # these have arguments in different positions than the add/print_param functions
 #
-#	eval_param_ifn       <param> <command>
-#	eval_print_param_ifn <param> <desc> <command>
-eval_param_ifn () {
+#	eval_param            <param> <command>
+#	eval_print_param      <param> <desc> <command>
+#	eval_param_ifn        <param> <command>
+#	eval_print_param_ifn  <param> <desc> <command>
+eval_param () {
 	local param
 	local command
-	local value
 
 	param="${1}"
 	IFS=' ' read -a command <<< "${2}"
 
-	[ -z "${!param}" ] \
-		&& value="$(eval "${command[*]}")" \
-		|| value="${!param}"
+	# [ ! -z "${DEBUG+set}" ] \
+	# 	&& >&2 echo "eval_param command: ${command[*]}"
+	add_param "$(eval "${command[*]}")" "${param}"
+}
 
-	add_param "${value}" "${param}"
+eval_print_param () {
+	local desc
+	[ ! -z "${3}" ] && desc="${2}"
+	eval_param "${1}" "${3:-${2}}"
+	print_param "${!1}" "${desc:-${1}}"
+}
+
+eval_param_ifn () {
+	local param
+	local command
+
+	param="${1}"
+	IFS=' ' read -a command <<< "${2}"
+
+	if [ -z "${!param}" ]; then
+		eval_param "${param}" "${command[*]}"
+	else
+		# [ ! -z "${DEBUG+set}" ] \
+		# 	&& >&2 echo "eval_param_ifn: value exists"
+		add_param "${!param}" "${param}"
+	fi
 }
 
 eval_print_param_ifn () {
 	local desc
 	[ ! -z "${3}" ] && desc="${2}"
-
 	eval_param_ifn "${1}" "${3:-${2}}"
 	print_param "${!1}" "${desc:-${1}}"
+}
+
+function cleanup() { tput cnorm; }
+trap cleanup EXIT
+
+spinner() {
+	local pid=$!
+	local delay=0.5
+	local i=0
+
+	tput civis
+	while ps -a | awk '{print $1}' | grep -q "${pid}"; do
+	    c=`expr ${i} % 4`
+	    case ${c} in
+	       0) printf '/' ;;
+	       1) printf '-' ;;
+	       2) printf '\\' ;;
+	       3) printf '|' ;;
+	    esac
+	    i=`expr ${i} + 1`
+	    sleep $delay
+	    printf "\b"
+	done
 }
 
 ## curl the provided URL, handle errors and cache
@@ -82,18 +133,22 @@ get_url () {
 	cache_file="${DATA_DIR}/$(echo "${1}" | md5sum | cut -d' ' -f1)"
 
 	if [ -f "${cache_file}" ] && [ "$(( $(date +"%s") - $(date -r "${cache_file}" +"%s") ))" -lt "${CACHE_EXPIRY}" ]; then
+		[ ! -z "${DEBUG}" ] && >&2 echo "Using cache for URL: ${1}"
 		cat "${cache_file}"
 	else
-		page_data="$(curl -sL -w "%{http_code}\n" "${1}")"
+		>&2 printf 'Getting URL: %s.. ' "${1}"
+		page_data=$(curl -sL -w '%{http_code}\n' "${1}")
 		http_code="${page_data:(-3)}"
+
 		if [ "${http_code}" = "200" ]; then
 			echo "${page_data%???}" | tee "${cache_file}"
 		else
 			>&2 echo "URL: ${1}"
 			>&2 echo "cache file: $(echo "${1}" | md5sum | cut -d' ' -f1)"
-			>&2 echo "HTTP Error: ${http_code}"
+			>&2 printf 'HTTP Error: %s\n\n' "${http_code}"
 			return 1
 		fi
+		>&2 printf "\r$(tput el)"
 	fi
 }
 
@@ -103,15 +158,20 @@ git_api_data () {	get_url "https://api.github.com/repos/${1}/${2}"; }
 # git_api_element <repo> <request> <element>
 git_api_element () { git_api_data "${1}" "${2}" | sed -En 's|.*"'"${3}"'"\W+"([^"]+)".*|\1|p'; }
 
+# git_repo_releases <repo> (<element>)
+git_repo_releases () { git_api_element "${1}" 'releases' "${2:-tag_name}" | sort -uV; }
+
 # git_latest_release <repo> (<element>)
 git_latest_release () { git_api_element "${1}" 'releases/latest' "${2:-tag_name}"; }
+# git_latest_release <repo>
+# git_latest_release () {	git_repo_releases "${1}" | tail -n1; }
 
 # git_repo_tags <repo> (<element>)
-git_repo_tags () { git_api_element "${1}" 'tags' "${2:-name}" | sort -uV;
-}
+git_repo_tags () { git_api_element "${1}" 'tags' "${2:-name}" | sort -uV; }
 
 # git_latest_tag <repo> (<element>)
 # git_latest_tag () {	git_api_element "${1}" 'tags' "${2:-name}" | sort -uV | tail -n1; }
+# git_latest_tag <repo>
 git_latest_tag () {	git_repo_tags "${1}" | tail -n1; }
 
 # alpine_package_version <package> <alpine version> <repos>
@@ -148,14 +208,14 @@ debian_package_version () {
 	fi
 
 	# either of these works
-#	package_version="$(get_url "https://sources.debian.org/api/src/${package}/" | grep -oP "\"suites\"[^}]*${debian_release}\"[^}]*version\D*\K[0-9\.\-]*")"
-	package_version="$(get_url "https://sources.debian.org/api/src/nginx/${debian_release}/" | grep -oP 'version"\:"\K([^\"]*)' | cut -d'+' -f1)"
+	package_version="$(get_url "https://sources.debian.org/api/src/${package}/" | grep -oP "\"suites\"[^}]*${debian_release}\"[^}]*version\D*\K[0-9\.\-]*")"
+	# package_version="$(get_url "https://sources.debian.org/api/src/${package}/${debian_release}/" | grep -oP 'version"\:"\K([^\"]*)' | cut -d'+' -f1)"
 
 	echo "${package_version}"
 }
 
 # pypi_api_XXXX <project>
-pypi_api_data () {	get_url "https://pypi.org/simple/${1}"; }
+pypi_api_data () { get_url "https://pypi.org/simple/${1}"; }
 pypi_api_versions () { pypi_api_data "${1}" | grep -oP "(?<=${1}-)[0-9.]{4,}(?=.tar.gz)" | sort -uV; }
 pypi_api_latest_version () { pypi_api_versions "${1}" | tail -n1; }
 
@@ -163,11 +223,14 @@ pypi_api_latest_version () { pypi_api_versions "${1}" | tail -n1; }
 py_musl_wheel_versions () { docker_api_repo_tags "${WHEEL_REPO}" | grep -oP "${1}\K([0-9.]+)(?=-py)" | sort -uV; }
 py_musl_wheel_latest () { py_musl_wheel_versions "${1}" | tail -n1; }
 
-parse_version_major () { echo "${1}" | awk -F \. '{print $1}'; }
-parse_version_minor () { echo "${1}" | awk -F \. '{print $1"."$2}'; }
+# return the 'X' for any 'X.Y.Z' versions provided as arguments
+parse_version_major () { echo "${1}" | xargs -n1 | grep -oP '(^\d*)' | sort -uV ; }
+
+# return the 'X.Y' for any 'X.Y.Z' versions provided as arguments
+parse_version_minor () { echo "${1}" | xargs -n1 | grep -oP '(^\d*\.\d*)' | sort -uV; }
 
 #
-# py_requireed_vesion() and python_get_module_from_string() needs a refactor,
+# py_required_vesion() and python_get_module_from_string() needs a refactor,
 # the whole python wheel thing was tacked on at the end, not really planned
 #
 
@@ -302,7 +365,7 @@ docker_api_get_repo () {
 	local repo && repo="${1}"
 	[[ "${repo}" != *"/"* ]] && repo="library/${repo}"
 
-	URL="https://registry.hub.docker.com/v2/repositories/${repo}/tags?page_size=100"
+	URL="https://registry.hub.docker.com/v2/repositories/${repo}/tags?page_size=1000"
 	while [ -n "${URL}" ]; do
 #		>&2 echo "Getting: ${URL}"
 		page="$(get_url "${URL}")"
@@ -441,15 +504,19 @@ get_manifest() {
 
 	manifest_file="${DATA_DIR}/manifest.${source_repo//\//_}.${source_image##*:}"
 
+	>&2 tput civis
+
 	if [ ! -f "${manifest_file}" ] || [ "$(( $(date +"%s") - $(date -r "${manifest_file}" +"%s") ))" -gt "${CACHE_EXPIRY}" ]; then
-		>&2 printf 'Fetching manifest: %s.. ' "${source_image}"
+		>&2 printf 'Fetching manifest: %s..           \b\b\b\b\b\b\b\b\b\b' "${source_image}"
 
 		manifest_cmd=("$(get_manifest_tool)" 'inspect' "${source_image}")
 		# pretty_manifest_cmd="$(echo "${manifest_cmd[*]}" | sed -r -e "s/(--)/\\\ \n\t\1/g")"
 		# >&2 printf '\n--- manifest command ---\n%s\n' "${pretty_manifest_cmd}"
 
+		# the spinner used in this way prevents 'error' being set
 		local error
-		error="$("${manifest_cmd[@]}" 2>&1 1>"${manifest_file}")";
+		error="$("${manifest_cmd[@]}" 2>&1 1>"${manifest_file}")" #&
+		# >&2 spinner
 
 		# if there's an error try and determine the cause so we can decide whether to
 		# cache the failure by keeping the empty manifest file:
@@ -477,12 +544,14 @@ get_manifest() {
 			return 1
 		fi
 
-		>&2 echo
+		>&2 printf '\r'
 	# else
 	# 	>&2 printf 'Using cached manifest: %s\n' "${manifest_file}"
 	fi
+	>&2 tput cnorm
 	echo "${manifest_file}"
 }
+
 
 # ifFunc <func>
 ifFunc () { type "${1}" 2> /dev/null | sed "s/${1}//" | grep -qwi function; }
